// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPI___JWT_Authentication.Data;

#nullable disable

namespace MinimalAPI___JWT_Authentication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241218173921_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinimalAPI___JWT_Authentication.Entities.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(35)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("User Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("VARCHAR");

                    b.HasKey("UserName");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserName = "Abdalkreem",
                            Password = "12121221"
                        },
                        new
                        {
                            UserName = "Islam",
                            Password = "121571021"
                        },
                        new
                        {
                            UserName = "Mohammed",
                            Password = "129763221"
                        });
                });

            modelBuilder.Entity("MinimalAPI___JWT_Authentication.Entities.WeatherForecast", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("DATE");

                    b.Property<string>("Summary")
                        .HasMaxLength(350)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("TemperatureC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(5, 2)")
                        .HasDefaultValue(0m);

                    b.ToTable("WeatherForecasts");
                });
#pragma warning restore 612, 618
        }
    }
}
